### ISSUE TITLE
Removing if-else branching

### ISSUE THREAD

**Issue by maxcell** [chardane/ClarifaiRuby#13]
Referring to [tag_image](https://github.com/chardane/ClarifaiRuby/blob/master/lib/clarifai_ruby/models/tag_image.rb#L26-L41).

Suggested code rewrite to follow `[]=` idiosyncrasy:

``` ruby
def generate_tags(tag_doc)
  concept_ids = tag_doc["concept_ids"] || []
  classes = tag_doc["classes"]
  probs = tag_doc["probs"]

  tags = []
  classes.each_with_index do |c, i|
    tags << Tag.new(c, probs[i], concept_ids[i])
  end
end
```

**Comment by chardane** [comment]
this is addressed in https://github.com/chardane/ClarifaiRuby/pull/12
