### ISSUE TITLE
v1 auth has been disabled

### ISSUE THREAD

**Issue by gregschwartz** [chardane/ClarifaiRuby#33]
The v1 authentication has been disabled, and now only v2 is usable. http://help.clarifai.com/api/transitioning-from-our-v1-to-our-v2-api

Would love to use this gem, it has by far the best documentation. Will you be updating the gem to support v2?

**Comment by maxcell** [comment]
Howdy there cool cat! We will be taking this library down now with the deprecation. I'd love for you to however see another community Ruby Gem that was made [here](https://github.com/nicholalexander/clarification). I think that it can be better equipped for your needs as supports API Keys! Hope this helps @gregschwartz!
